export const DEFAULT_ALL_IN_ONE_ENV: Record<string, string> = {
  USER: "gem",
  USER_UID: "1000",
  USER_GID: "1000",
  DISPLAY: ":99.0",
  DISPLAY_DEPTH: "24",
  WORKSPACE: "/workspace",
  LOG_DIR: "/var/log/gem",
  PUBLIC_PORT: "8080",
  AUTH_BACKEND_PORT: "8081",
  SANDBOX_SRV_PORT: "8091",
  WAIT_PORTS: "8091",
  AIO_BASE_URL: "http://localhost:8091",
  MAX_SHELL_SESSIONS: "10",
  NODE_CODE_EXEC_VERSION: "node22",
  NODEJS_REPL_PORT_20: "8192",
  NODEJS_REPL_PORT_22: "8092",
  NODEJS_REPL_PORT_24: "8392",
  DISABLE_NODEJS_REPL: "false",
  DISABLE_JUPYTER: "true",
  DISABLE_CODE_SERVER: "true",
  DISABLE_BROWSER: "true",
  DISABLE_MCP_BROWSER: "true",
  DISABLE_VNC: "true",
  ENABLE_CJK_IME: "false",
  MCP_SERVER_BROWSER_PORT: "8100",
  BROWSER_REMOTE_DEBUGGING_PORT: "9222",
  BROWSER_EXECUTABLE_PATH: "/usr/local/bin/browser",
  AGENT_BROWSER_EXECUTABLE_PATH: "/usr/local/bin/browser",
  BROWSER_EXTRA_ARGS: "",
  BROWSER_DOWNLOAD_DIR: "",
  BROWSER_NO_SANDBOX: "",
  BROWSER_LANG: "en-US",
  CHROME_UI_LANG: "",
  BROWSER_USER_AGENT: "",
  DISPLAY_WIDTH: "1280",
  DISPLAY_HEIGHT: "1024",
  VNC_SERVER_PORT: "5900",
  WEBSOCKET_PROXY_PORT: "6080",
  JUPYTER_LAB_PORT: "8888",
  CODE_SERVER_PORT: "8200",
  OPENCODE_PORT: "4096",
  TINYPROXY_PORT: "8118",
  LOG_STDOUT_SERVER: "false",
  LOG_TOOL_TRACE: "false",
  RUN_HOOK_INIT: "",
  RUN_HOOK_PRE_SERVICES: "",
  RUN_HOOK_POST_READY: "",
  RUN_HOOKS_STRICT: "false",
  SANDBOX_SHUTDOWN_HOOKS: "",
  SANDBOX_SHUTDOWN_HOOKS_TIMEOUT: "30",
  AIO_CLI_SKILL_ENABLED: "false",
  AIO_SKILLS_PATH: "",
  EXTRA_MCP_SERVERS: "",
  PUBLIC_LISTEN_IPV4: "0.0.0.0",
  PUBLIC_LISTEN_IPV6: "[::]",
  JWT_PUBLIC_KEY: "",
  HOMEPAGE: "",
  GITHUB_TOKEN: "",
  BROWSER_INIT_COOKIES: "",
  BROWSER_URL_BLOCKLIST: "",
  BROWSER_URL_ALLOWLIST: "",
  PROXY_BYPASS_LIST: "",
  DNS_OVER_HTTPS_TEMPLATES: "",
  PYTHON_CODE_EXEC_VERSION: "python3",
  LANG: "en_US.UTF-8",
  LANGUAGE: "en_US:en",
  LC_ALL: "en_US.UTF-8",
  TZ: "Asia/Shanghai",
  OTEL_SDK_DISABLED: "false",
  OTEL_PYTHON_DISABLED_INSTRUMENTATIONS: "redis",
  PYTHONPATH: "",
  PYTHONUNBUFFERED: "1",
  PYTHONIOENCODING: "utf-8",
  RUNTIME_LOGDIR: "/var/log/gem",
  UV_TOOL_BIN_DIR: "/usr/local/bin/",
  UV_TOOL_DIR: "/usr/local/share/uv/tools",
  GO_PATH: "/usr/local/go",
  CC: "gcc",
  CXX: "g++",
  FNM_DIR: "/opt/fnm",
  NODEJS_DIR: "/opt/nodejs",
};

export function buildAllInOneEnv(params: {
  workspaceDir: string;
  port: number;
  apiKey?: string;
  overrides?: Record<string, string>;
}): Record<string, string> {
  return {
    ...DEFAULT_ALL_IN_ONE_ENV,
    WORKSPACE: params.workspaceDir,
    PUBLIC_PORT: String(params.port),
    ...(params.apiKey ? { SANDBOX_API_KEY: params.apiKey } : {}),
    ...(params.overrides ?? {}),
  };
}
